model:
  name: bert-base-uncased
  max_len: 256
  dropout_rate: 0.3

training:
  epochs: 50
  batch_size: 16
  learning_rate: 2e-5
  warmup_steps: 0
  weight_decay: 0.01
  accumulation_steps: 4
  patience: 5

data:
  train_file: Train-sheet.csv
  test_file: Test-sheet.csv
  validation_split: 0.2